import type { DbType } from "../types";
import { TABLES } from "./types";

/**
 * Same three tables on every database; only the column types differ.
 * Tables are prefixed `tl_` so they can sit next to a customer's own tables, and timestamps are
 * stored as ISO text so they sort and compare the same way everywhere.
 */
function types(type: DbType) {
  const id = {
    sqlite: "INTEGER PRIMARY KEY AUTOINCREMENT",
    postgres: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    mysql: "INT AUTO_INCREMENT PRIMARY KEY",
    mssql: "INT IDENTITY(1,1) PRIMARY KEY",
  }[type];
  const big = { sqlite: "TEXT", postgres: "TEXT", mysql: "LONGTEXT", mssql: "NVARCHAR(MAX)" }[type];
  // SQL Server's VARCHAR can't hold names in Hindi or other scripts; NVARCHAR can.
  const vc = (n: number) => (type === "mssql" ? `NVARCHAR(${n})` : `VARCHAR(${n})`);
  const int = type === "sqlite" ? "INTEGER" : "INT";
  const tail = type === "mysql" ? " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" : "";
  return { id, big, vc, int, tail };
}

/**
 * Columns added after the first release. They are added to existing tables when missing (each driver
 * checks first), so a database created by an older version upgrades itself. Nullable, so old rows stay valid.
 */
export function addedColumns(type: DbType): { table: string; column: string; def: string }[] {
  const { big, vc } = types(type);
  return [
    { table: TABLES.jobs, column: "jd_hash", def: `${vc(64)} NULL` },
    { table: TABLES.candidates, column: "resume_hash", def: `${vc(64)} NULL` },
    { table: TABLES.candidates, column: "gate_missing", def: `${big} NULL` },
  ];
}

export function ddl(type: DbType): string[] {
  const { id, big, vc, int, tail } = types(type);
  const create = (table: string, cols: string[]) =>
    type === "mssql"
      ? `IF OBJECT_ID(N'${table}', N'U') IS NULL CREATE TABLE ${table} (${cols.join(", ")})`
      : `CREATE TABLE IF NOT EXISTS ${table} (${cols.join(", ")})${tail}`;

  return [
    create(TABLES.jobs, [
      `id ${id}`,
      `title ${vc(255)} NOT NULL`,
      `jd_text ${big} NOT NULL`,
      `requirements ${big} NOT NULL`,
      `created_at ${vc(40)} NOT NULL`,
    ]),
    create(TABLES.candidates, [
      `id ${id}`,
      `job_id ${int} NOT NULL`,
      `name ${vc(255)} NOT NULL`,
      `email ${vc(255)} NOT NULL`,
      `candidate_role ${vc(255)} NOT NULL`,
      `file_name ${vc(500)} NOT NULL`,
      `resume_text ${big} NOT NULL`,
      `score ${int} NOT NULL`,
      `ai_verdict ${vc(20)} NOT NULL`,
      `hr_status ${vc(20)} NOT NULL`,
      `note ${vc(1000)} NOT NULL`,
      `source ${vc(20)} NOT NULL`,
      `provider ${vc(30)} NOT NULL`,
      `model ${vc(120)} NOT NULL`,
      `report ${big} NOT NULL`,
      `created_at ${vc(40)} NOT NULL`,
      `decided_at ${vc(40)} NULL`,
    ]),
    create(TABLES.audit, [
      `id ${id}`,
      `at ${vc(40)} NOT NULL`,
      `actor ${vc(100)} NOT NULL`,
      `action ${vc(30)} NOT NULL`,
      `candidate_id ${int} NULL`,
      `job_id ${int} NULL`,
      `summary ${vc(500)} NOT NULL`,
      `detail ${big} NULL`,
    ]),
    create(TABLES.history, [
      `id ${id}`,
      `candidate_id ${int} NOT NULL`,
      `from_status ${vc(20)} NULL`,
      `to_status ${vc(20)} NOT NULL`,
      `note ${vc(1000)} NOT NULL`,
      `created_at ${vc(40)} NOT NULL`,
    ]),
  ];
}

export function insertSql(table: string, values: Record<string, unknown>, mid = "", tail = "") {
  const cols = Object.keys(values);
  return {
    sql: `INSERT INTO ${table} (${cols.join(", ")})${mid} VALUES (${cols.map(() => "?").join(", ")})${tail}`,
    params: cols.map((c) => values[c] ?? null),
  };
}

/** Turn `?` placeholders into the numbered form a driver wants ($1 for Postgres, @p1 for SQL Server). */
export const numbered = (sql: string, prefix: string) => {
  let i = 0;
  return sql.replace(/\?/g, () => `${prefix}${++i}`);
};
